# Generated by Django 5.2.3 on 2025-07-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="session_id",
        ),
    ]
