# Generated by Django 5.2.3 on 2025-07-22 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0001_initial"),
        ("meeting", "0002_remove_response_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingSession",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "current_duration",
                    models.IntegerField(
                        help_text="Duration in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(3600),
                        ],
                    ),
                ),
                (
                    "current_question_index",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="director.meeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParticipantSession",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "sessiontoken",
                    models.CharField(
                        help_text="Used to identify previous meeting Session by the user",
                        max_length=66,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="director.meeting",
                    ),
                ),
            ],
        ),
    ]
