# Generated by Django 5.2.3 on 2025-07-22 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0003_meetingsession_participantsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="participant_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="meeting.participantsession",
            ),
        ),
    ]
