# Generated by Django 5.2.3 on 2025-07-22 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meeting", "0004_response_participant_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="total_responses",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
