# Generated by Django 5.2.3 on 2025-07-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="meetings_created_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_participants_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_responses_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
