# Generated by Django 5.2.3 on 2025-07-04 18:12

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_code", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=200)),
                (
                    "duration",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="Meeting Duration must be greater than or equal to 15 minutes",
                            ),
                            django.core.validators.MaxValueValidator(
                                120, message="Meeting Duration cannot exceed 2 hours"
                            ),
                        ]
                    ),
                ),
                (
                    "questions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=150),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "director",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
