# Generated by Django 5.2.3 on 2025-07-05 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="questions",
        ),
        migrations.AddField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="last_run",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="meeting",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="director",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="duration",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        15,
                        message="Meeting Duration must be greater than or equal to 15 minutes",
                    ),
                    django.core.validators.MaxValueValidator(
                        120, message="Meeting Duration cannot exceed 2 hours"
                    ),
                ]
            ),
        ),
    ]
