# Generated by Django 5.2.3 on 2025-07-05 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0002_remove_meeting_questions_meeting_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
