# Generated by Django 5.2.3 on 2025-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0005_question_created_at_question_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="participant_count",
            field=models.IntegerField(default=0),
        ),
    ]
