# Generated by Django 5.2.3 on 2025-07-12 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["position"]},
        ),
        migrations.AlterField(
            model_name="question",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="director.meeting",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="position",
            field=models.PositiveIntegerField(
                help_text="Question's index position in the meeting"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("meeting", "position")},
        ),
    ]
