# Generated by Django 5.2.3 on 2025-07-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="duration_in_seconds",
            field=models.PositiveIntegerField(
                default=0, help_text="Meeting duration in seconds"
            ),
        ),
    ]
