# Generated by Django 5.2.3 on 2025-07-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0002_meeting_duration_in_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="total_questions_asked",
            field=models.PositiveIntegerField(
                default=0, help_text="Amount of questions asked during the meeting"
            ),
        ),
    ]
