# Generated by Django 5.2.3 on 2025-07-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0003_meeting_total_questions_asked"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="summarized_meeting",
            field=models.JSONField(default=dict),
        ),
    ]
